// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yrmvcqlyjuhnylmsihrr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlybXZjcWx5anVobnlsbXNpaHJyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5NTYxMjEsImV4cCI6MjA3MDUzMjEyMX0.HFYbzVg3a4E_EQwjAa9NBtEWRWUbKOiOxaDW5dxpIGs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});